name: Push web folder to BreathingSpace-Web repo

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  master:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: push to other repo
      run: |
        git remote add upstream https://$API_TOKEN_GITHUB@github.com/InFact-coop/BreathingSpace-Web.git
        git push upstream `git subtree split --prefix web`:refs/remotes/upstream/master --force

  staging: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: push to other repo
      run: |
        git remote add upstream https://$API_TOKEN_GITHUB@github.com/InFact-coop/BreathingSpace-Web.git
        git checkout -b origin/staging
        git push upstream `git subtree split --prefix web`:refs/remotes/upstream/staging --force
